[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/njace/"
  to = "https://www.njace.us"
  status = 301

[[redirects]]
  from = "/recruitment/"
  to = "https://njace.us/data-repository/recruitment/"
  status = 301

[[redirects]]
  from = "/sign-up/"
  to = "https://visitor.r20.constantcontact.com/manage/optin?v=001dZZfSJUF90BZNI5fME5hTWzA5UnczZ0YKeSR30lONk_Dr6aHK1tJ0CQHBZqsxG3T3QjmL868lPbAz6TY8d7cIcP8ffXKCLwYA7uerBhDG4oR98QkPWfpny5ouEoB5r7-sMvDB9uMc0-EWxXUK9fgw5bjhFItTb6G"
  status = 301

[[redirects]]
  from = "/research/"
  to = "https://njace.us/research/current-studies/"
  status = 301

[[redirects]]
  from = "/youtube/"
  to = "https://www.youtube.com/channel/UCfRG4te3SNBxu-Qe01PsiCQ"
  status = 301

[[redirects]]
  from = "/facebook/"
  to = "https://www.facebook.com/NJAutismCenterofExcellence/"
  status = 301
