[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/njace/"
  to = "https://www.njace.us"
  status = 301

[[redirects]]
  from = "/recruiting/"
  to = "https://njace.us/data-repository/recruitment/"
  status = 301